language: groovy

jdk:
  - oraclejdk8

sudo: required

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - WRAPPER=$(find . -type f -executable -name gradlew -print -quit)
  - $WRAPPER buildAll
